# Site settings
name: kevin
email: kevin031995@gmail.com
url: url
description: "Kevin Herrera, Game Designer blog and portfolio"
author: "Kevin Herrera"
title: "Game Designer Portfolio"
permalink: pretty
baseurl: /

# social
github:
  username: AaronClaros

twitter:
  username: aaronclaros

linkedin:
  username: kevin-aaron-herrera-claros-192375119

# Work contact info
contactInfo:
  resumePath: /assets/files/Kevin-Herrera_Resume-GD.pdf
  contactEmail: kevin031995@gmail.com