# Site settings
name: kevin
email: kevin031995@gmail.com
url: url
description: "Kevin Herrera, Game Designer blog and portfolio"
author: "Kevin Herrera"
title: "Kevin Herrera - Portfolio"
permalink: pretty
baseurl: /

# social
github:
  username: AaronClaros

twitter:
  username: KevinHerreraGD

linkedin:
  username: kevin-aaron-herrera-claros-192375119
